services:
  server:
    build:
      context: ./server
      dockerfile: Dockerfile.dev
    environment:
      SPS_DATA_DIR: /data
      SPS_BIND: :8080
      SPS_LOGIN_EMAIL: me@example.com
      SPS_DOCKER_SOCK: unix:///var/run/docker.sock
      SMTP_USER: ""
      SMTP_PASSWORD: ""
    volumes:
      - ${SPS_E2E_DATA_DIR}:/data
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - "${SPS_E2E_API_PORT}:8080"
    networks:
      - sps-net

networks:
  sps-net:
    external: true
