services:
  server:
    build:
      context: ./server
      dockerfile: Dockerfile.dev
    environment:
      PCODER_DATA_DIR: /data
      PCODER_BIND: :8080
      PCODER_LOGIN_EMAIL: me@example.com
      PCODER_DOCKER_SOCK: unix:///var/run/docker.sock
      SMTP_USER: ""
      SMTP_PASSWORD: ""
    volumes:
      - ${PCODER_E2E_DATA_DIR}:/data
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - "${PCODER_E2E_API_PORT}:8080"
    networks:
      - pcoder-net

networks:
  pcoder-net:
    external: true
